# azure-pipelines.yml
trigger:
  branches:
    include:
      - dev

variables:
  imageName: 'akdev'
  acrName: 'saviacr2025.azurecr.io'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build Image
    pool:
      name: Default
    steps:
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'saviacr2025-connection'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          $(tag)

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: BuildAndPush
  jobs:
  - job: DeployToAks
    displayName: Deploy to AKS Cluster
    pool:
      name: Default
    steps:
    - task: AzureCLI@2
      displayName: Set AKS context
      inputs:
        azureSubscription: 'saviarm_connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group RG1 --name MyAKSCluster --overwrite-existing

    - script: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/secret.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
      displayName: Apply Kubernetes Manifests
