apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
  namespace: akdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: akswebapp
        image: saviacr2025.azurecr.io/akdev:7
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
