apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
  namespace: akdev
type: Opaque
stringData:
  dbcn: "Server=webapiaks.database.windows.net;Database=db_AngularAPI;User=azsqlsrv;Password=sqlsrv@123;TrustServerCertificate=True;"