apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: akdev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <BASE64_ENCODED_DOCKER_CONFIG_JSON>  # Replace with actual base64 content or use kubectl to create
